# Makefile for Queue Implementation with Circular Linked List
# Jason Lin 
# 02/11/2024
# CPSC 2120 

compile:
	g++ -Wall IntegerArrayQueue.cpp T7.cpp -o queue.exe
	make run
run:	
	./queue.exe
clean:
	rm queue.exe
